name: test

on:
  workflow_dispatch:
    inputs:
      SOMENUM:
        description: 'gimme a number'
        default: '0'
        required: true
      ANOTHERNUM:
        description: 'how about another number'
        default: '0'
        required: true
jobs:
  write-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write inputs to AUDIT.md
        run: |
          TODAY=$(date +'%Y-%m-%d')
          echo "## Audit Log - $TODAY" >> AUDIT.md
          echo "" >> AUDIT.md
          echo "WHATEVER: ${{ github.event.inputs.SOMENUM }}" >> AUDIT.md
          echo "" >> AUDIT.md
          echo "ANOTHER: ${{ github.event.inputs.ANOTHERNUM }}" >> AUDIT.md
          echo "" >> AUDIT.md
          echo "Workflow Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> AUDIT.md
          echo "" >> AUDIT.md
          echo "" >> AUDIT.md
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add AUDIT.md
          git commit -m "Update AUDIT.md with inputs"
          git push
